# Generated by Django 2.2 on 2019-08-10 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinformation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customerinformation',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='customerinformation',
            name='pin_code',
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.IntegerField()),
                ('pin_code', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_app.CustomerInformation')),
            ],
        ),
    ]
